### PR TITLE
changed try! to ?

### PR DESCRIPTION
**Pull request by greenpdx**
I just update try! to ? 
But I also have a branch on my repo that changes Fetch structure by adding  
email: Option<&'static [u8]>,

then in parse_fetches I added 
AttributeValue::BodySection {section, index, data} => fetch.email = data,

that gives me the email data at the higher level where I use parse_mail() to get the email.
is that Ok?

### CODE REVIEW

**Comment by jonhoo** [comment]
I believe the `try!`s were there because @mattnenterprise wanted to support older versions of Rust back in the day. I'm happy to switch to `?` though. It's much more ergonomic! I'll merge once the CI tests pass :)

As for the changes to `Fetch`, that seems like an excellent change! Could you please post that as a separate PR?

**Comment by jonhoo** [comment]
Also, as a side-note for when you put the `Fetch` change in a new PR, could you change the name of the field to `body` and make it `pub(crate)`, and then add an accessor method like we have for the other fields?

**Comment by greenpdx** [comment]
OK,  but I do not know how to create a new PR when one is pending

**Comment by greenpdx** [comment]
I think it is adding my new changes to this PR not good

**Comment by jonhoo** [comment]
Ah, you'll have to create a new branch! If you don't know how, you can run these commands in your copy of the repository:
```console
$ git branch body
$ git reset ba8afa79182ed31e9d98b1e1b2dc3c8be066d2ef
$ git push --force-with-lease
$ git checkout body
$ git push -u origin body
```
This creates a new branch `body`, which includes all your later commits, and leaves only your first commit in this Pull Request. You can then go to https://github.com/mattnenterprise/rust-imap, and there should be a yellow bar asking if you want to create a new Pull Request for the `body` branch. Click "Create Pull Request" (or whatever the button says), and that should make the second PR! Any new commits you make and push will also go to that new PR :)

**Comment by jonhoo** [comment]
Perfect! Thank you!

**Pull request merged**
