### PR TITLE
Use cargo-tarpaulin instead of kcov/cargo-travis

### LINKED ISSUE #45: Switch from kcov to cargo-tarpaulin
@mattnenterprise in [`addr2line`](https://github.com/gimli-rs/addr2line), we're [switching](https://github.com/gimli-rs/addr2line/pull/54) to `cargo-tarpaulin` for code coverage, and completely removing `cargo-travis`. Might be something we'll want to do here as well.

### PR DESCRIPTION
**Pull request by jonhoo**
Fixes #45.

### CODE REVIEW

**Comment by mattnenterprise** [comment]
@jonhoo Do you know why the amount of coverage changed ?

**Comment by jonhoo** [comment]
Unclear. It may be that the new tool measures coverage differently?

**Comment by jonhoo** [comment]
Also, our coverage is pretty poor, but it's unclear we can make it much better without an actual server to connect to. I wonder if there are IMAP test servers out there?

**Comment by jonhoo** [comment]
One alternative might be to spin up a real IMAP server for testing. Maybe https://github.com/uiri/SEGIMAP could be of use to us. There's also [GreenMail](http://www.icegreen.com/greenmail/), but it's in Java, so may be more of a pain to set up.

**Comment by mattnenterprise** [comment]
It looks like they do measure things differently. For example `cargo-travis` shows the declaration of an enum in its coverage, but it looks like `cargo-tarpauling` doesn't. I'm fine with this as it doesn't effect coverage much.

As for using an IMAP server. I would like to try as much as possible to not bring in a server. If we really had to I would prefer it be a server in rust that we could start and stop directly in the test code itself. I really don't want to make the tests more complicated than a simple `cargo test` command.

**Comment by jonhoo** [comment]
@mattnenterprise I completely agree. I was imagining that `cargo test` would still be all that would be required, and that the test suite would spin up the server. The reason I think it would be advantageous is that we could test way more of the code that way. Things like IDLE, authentication, message fetching, etc.

**Comment by jonhoo** [comment]
Regardless, I think this should be merged.

**Comment by mattnenterprise** [comment]
As long as the the only thing needed is `cargo test` I would be happy with it.

**Pull request merged**
