### PR TITLE
Add passing back the email in [u8]

### PR DESCRIPTION
**Pull request by greenpdx**
Pass back email in [u8] so it can be parsed by mailparse::parse_email
added email to fetch structure and used 
AttributeValue::BodySection {section: _, index: _, data} => fetch.email = data,
to get it

### CODE REVIEW

**Comment by jonhoo** [comment]
Great! Could you please also rename the field + method to be called `body` (as that's also the name of the field in the IMAP standard)?

**Comment by greenpdx** [comment]
But it is both header and body.

**Comment by jonhoo** [comment]
It's the `BodySection` of the email though, right?

**Comment by jonhoo** [comment]
Thanks! I'll merge once the tests pass :D

**Comment by jonhoo** [comment]
@mattnenterprise minor version bump

**Comment by greenpdx** [comment]
Now I can start working on my application. ;D  I took your buzz and hacked it up greatly. Your rust is much better than mine. I might need some help.

**Comment by jonhoo** [comment]
Haha, I appreciate the contribution! Once @mattnenterprise gets around to it, hopefully we'll also get a release out with your changes. I'd recommend using `rustfmt` and `clippy`, especially when you're just starting out, as they help a lot with writing cleaner and more idiomatic code. I've also done a bunch of live-coding sessions that you can see [here](https://www.youtube.com/playlist?list=PLqbS7AVVErFgY2faCIYjJZv_RluGkTlKt) if you're interested :)

**Pull request merged**
